### ISSUE TITLE
Enviar Comandos

### ISSUE THREAD

**Issue by w3nder** [evertonsena/ms-gps-tracker#1]
Existe alguma forma de enviar comando pro dispositivo?

Tava olhando o código é consegui fazer o bloqueio da bomba de gasolina colocando o comando direto no StreamSocketTk103bService.php

 $this->response = "LOAD";
 $this->response = "**,imei,J;"; 

Ai quando sobe o servidor ele já corta a gasolina. 
Existe alguma forma de eu enviar o comando fora do servidor?

**Comment by evertonsena** [comment]
Oi Weender.

A proposta do micro serviço é apenas ouvir o rastreador  e persistir os dados recebidos. As respostas dadas ao dispositivos tem como objetivo informa o recebimento.

Desconheço uma forma de enviar informações para o rastreador utilizando stream socket. Apenas através de SMS's.

Quando você diz que colocou o response direto na classe e dessa forma foi capaz de fazer o bloqueio da bomba. Essa implementação foi testada com o dispositivo? O mesmo cortou o combustível do veículo?

**Comment by w3nder** [comment]
Sim, cortou na hora, é pra liberar a bomba foi só mudar o comando o prazo do servidor responder 
 a gasolina liberou é o dispositivo do carro apitou, ai ligou novamente...

foi bem rápido.

**Comment by evertonsena** [comment]
Isso é bem interessante. Farei alguns testes. 
E como você chegou a conclusão que o response tem que ser: "**,imei,J;" para ativar o bloqueio da bomba ? imei = número imei do dispositivo, certo?

**Comment by w3nder** [comment]
**,imei:864180033644985,J; / Corta a Gasolina
**,imei:864180033644985,K; / Libera a Gasolina

864180033644985 é o numero do Imei do GPS

Aqui a lista completa dos protocolo
https://drive.google.com/file/d/0B__a1KVH5xh_dlZiY0x0bktpdnhuZTlZZFdVMkZDclg4Y3lZ/view

Eu também to testando aqui. qualquer solução que eu encontrar te informo.

**Comment by evertonsena** [comment]
Essa lista vai ser muito útil, obrigado.
Se o dispositivo pode receber comandos via stream, isso abre grandes possibilidades. O MS pode ser estendido para realizar as demais ações. Isso gera uma economia de recursos, como por exemplo o envio de SMS. Vamos nos falando sobre o andamento dos nossos testes.

Estou pesquisando servidores que permitam escutar portas maiores que 1023 para hospedar esse micro serviço. Me indica algum?
